#title: Suleman Rasheed
logo : /images/Profile_Pic.jpg
#logo: relative path of the image
#description: add text under the fig/dp
#show_downloads: true
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
#theme: minima

title: Suleman Rasheed
description: Biomedical Engineer | Data Scientist
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
