title: Suleman Rasheed
logo : /images/Profile_Pic.jpg
#logo: relative path of the image
#description: add text under the fig/dp
#show_downloads: true
#theme: jekyll-theme-minimal
theme: jekyll-theme-slate
#theme: minima
description: "Biomedical Engineer | Data Scientist"
