#title: Suleman Rasheed
logo : /images/Profile_Pic.jpg
#logo: relative path of the image
#description: add text under the fig/dp
#show_downloads: true
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
#theme: minima

title: Suleman Rasheed
description: Data Science Expert (PhD) | Turning data into insight through analytics, modelling, and visualisation.
theme: jekyll-theme-cayman
google_analytics: G-FWC3J5C41R
markdown: kramdown
kramdown:
  input: GFM
